name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Установка зависимостей
        run: npm install

      - name: Запуск тестов
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Vercel CLI
        run: npm install -g vercel

      - name: Деплой в Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
